version: "3.0"

services:
  liquidsoap:
    build:
      context: liquidsoap
      args:
        gitbranch: master
        version: 1.5.0
        buildnumber: 2857
    image: privyplace/liquidsoap:master-1.5.0-2857
    container_name: liquidsoap
    command: /radio/live.liq
    restart: unless-stopped
    networks:
      - default
    expose:
    - "8500"
    - "8081"
    - "9090"
    ports:
    - 10000:10000/udp
    - 10001:10001/udp
    - 8500:8500/tcp
    volumes:
     - ./radio:/radio
     - ./hls:/hls
  nginx:
    build:
      context: nginxhls
    image: privyplace/nginxhls:v1
    container_name: nginx
    restart: unless-stopped
    networks:
     - default
    expose:
    - "80"
    ports:
     - 8080:80/tcp
    volumes:
     - ./hls:/hls
     - ./nginxhls/stream.conf:/etc/nginx/conf.d/stream.conf

networks:
  default:
